name: Bump patch version

on:
  push:
    branches: [ ci ]

jobs:
  build-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Bump patch version
        run: |
          npm install
          npm run patchVersionBump
          git status
          phoenix_version=`node -p "require('./package.json').version"`
          echo "PHOENIX_VERSION=${phoenix_version}" >> $GITHUB_ENV
        shell: bash

      - name: Create Bump patch version Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'ci: bump patch version to ${{ env.PHOENIX_VERSION }}'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '[Release BOT] Bump patch version to ${{ env.PHOENIX_VERSION }}'
          add-paths: |
            package.json
            src/config.json
          body: |
            Bump patch version to ${{ env.PHOENIX_VERSION }}
            - Auto-generated by `patch-version-bump.yml` action
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
